module.exports = {
  'en': {
    'system.error': 'System error',
    'request.fail': 'System error',
    'request.success': 'Request successful',
    'company.companyName' : 'Company Name',
    'company.shortName' : 'Short Name',
    'company.nationalName' : 'International Name',
    'company.businessType' : 'Business Type', 
    'company.taxCode' : 'Tax Code',
    'company.registrationAddress' : 'Registration Address',
    'company.tradingAddress' : 'Trading Address',
    'company.phone' : 'Phone',
    'company.fax' : 'Fax', 
    'company.email' : 'Email', 
    'company.website' : 'Website',
    'company.foundDing' : 'Founding Date',
    'company.numEmployee': 'Number of Employees',
    'company.representName' : 'Representative Name',
    'company.representPosition' : 'Representative Position',
    'company.representAddress' : 'Representative Address',
    'company.career' : 'Careers',
    'company.existed': 'Company already exists',
    'company.notfound': 'Company not found',
    'company.status.invalid': 'Company status invalid',
    'taxcode.is.existed': 'Tax Code already exists',
    'usermapping.roletype': 'Role type',
    'usermapping.roletype.invalid': 'Role type invalid',
    'usermapping.sourceType': 'Source type',
    'usermapping.sourceType.invalid': 'Source type invalid',
    'usermapping.users.not.empty': 'User list can not empty',
    'usermapping.users.invalid': 'User list invalid',
    'usermapping.users.state': 'State',
    'usermapping.users.position': 'Position',
    'usermapping.users.state.invalid': 'User state invalid',
    'usermapping.companyId': 'Company ID',
    'usermapping.users.list.exist': 'Account already exists',
    'usermapping.token.email.active.invalid': 'Account invalid',
    'usermapping.token.email.reactive.invalid': 'Account has been activated',
    'usermapping.no.permision': 'No permission',
    'entity.entityName': 'Group name',
    'entity.groupType': 'Group type',
    'entity.notfound': 'Entity not found',
    'key.id.not.empty': 'Id can not empty',
    'info.notfound': 'Info not found',
    'token.invalid': 'Token invalid',
    'pakage': 'Package',
    'pakage.packageName': 'Package name',
    'pakage.procurementPlan': 'Procurement Plan',
    'pakage.offeree': 'Group Offeree',
    'pakage.field': 'Field',
    'pakage.orderProfile': 'Order Profile',
    'pakage.biddingType': 'Bidding Type',
    'pakage.contractType': 'Contract Type',
    'pakage.foundingSource': 'Funding Source',
    'pakage.fromContractDate': 'From Contract Date',
    'pakage.toContractDate': 'To Contract Date',
    'pakage.fromReceiveDate': 'From Receive Date',
    'pakage.toReceiveDate': 'To Receive Date',
    'pakage.insuranceFee': 'Insuance Fee',
    'pakage.receiveBidLocation': 'Receive Bid Location',
    'pakage.workeplace': 'Workplace',
    'pakage.openLocation': 'Bid opening location', 
    'pakage.estimate': 'Estimate',
    'pakage.existed': 'Package already exists',
    'pakage.notfound': 'Package not found',
    'pakage.biddingType.not.include': 'Bidding type invalid',
    'pakage.notiType.invalid': 'Notification type invalid',
    'pakage.status.invalid': 'Package status invalid',
    'bidding.cost': 'Bidding Cost',
    'bidding.entity': 'Bidding offeree',
    'bidding.startDate': 'Start date',
    'bidding.endDate': 'End date',
    'bidding.attackFiles': 'Attachment files',
    'bidding.notfound': 'Bidding not found',
    'bidding.existed': 'Offeree already exists',
  },
  'vi': {
    'system.error': 'Lỗi hệ thống',
    'request.fail': 'Lỗi hệ thống',
    'request.success': 'Thành công',
    'company.companyName' : 'Tên công ty',
    'company.shortName' : 'Tên rút gọn',
    'company.nationalName' : 'Tên quốc tế',
    'company.businessType' : 'Loại hình', 
    'company.taxCode' : 'Mã số thuế',
    'company.registrationAddress' : 'Địa chỉ đăng ký',
    'company.tradingAddress' : 'Địa chỉ giao dịch',
    'company.phone' : 'Điện thoại',
    'company.fax' : 'Fax', 
    'company.email' : 'Email', 
    'company.website' : 'Website',
    'company.foundDing' : 'Ngày thành lập',
    'company.numEmployee': 'Số nhân viên',
    'company.representName' : 'Tên người đại diện',
    'company.representPosition' : 'Vị trí người đại diện',
    'company.representAddress' : 'Địa chỉ người đại diện',
    'company.career' : 'Ngành nghề',
    'company.existed': 'Công ty đã tồn tại',
    'company.notfound': 'Không tìm thấy công ty',
    'company.status.invalid': 'Trạng thái không hợp lệ',
    'taxcode.is.existed': 'Mã số thuế đã tồn tại',
    'usermapping.roletype': 'Quyền hạn',
    'usermapping.roletype.invalid': 'Quyền hạn không hợp lệ',
    'usermapping.sourceType': 'Phân loại',
    'usermapping.sourceType.invalid': 'Phân loại không hợp lệ',
    'usermapping.users.not.empty': 'Danh sách tài khoản không được để trống',
    'usermapping.users.invalid': 'Danh sách tài khoản không hợp lệ',
    'usermapping.users.state': 'Trạng thái',
    'usermapping.users.position': 'Vị trí',
    'usermapping.users.state.invalid': 'Trạng thái tài khoản không hợp lệ',
    'usermapping.companyId': 'Mã công ty',
    'usermapping.users.list.exist': 'Tài khoản đã tồn tại',
    'usermapping.token.email.active.invalid': 'Tài khoản xác thực không hợp lệ',
    'usermapping.token.email.reactive.invalid': 'Tài khoản đã được kích hoạt',
    'usermapping.no.permision': 'Bạn không phải là quản lý, không đủ thẩm quyền',
    'usermapping.email.existed': 'Các email sau {0} đã tồn tại trong hệ thống ',
    'entity.entityName': 'Tên nhóm',
    'entity.entityType': 'Phân loại nhóm',
    'entity.notfound': 'Không tìm thấy nhóm',
    'entity.entityType.invalid': 'Phân loại nhóm không hợp lệ',
    'key.id.not.empty': 'Id ko được để trống',
    'info.notfound': 'Không tìm thấy thông tin',
    'token.invalid': 'Mã xác thực không hợp lệ',
    'pakage': 'Gói thầu',
    'pakage.packageName': 'Tên gói thầu',
    'pakage.procurementPlan': 'Kế hoạch lựa chọn nhà thầu',
    'pakage.offeree': 'Nhóm mời thầu',
    'pakage.field': 'Lĩnh vực',
    'pakage.orderProfile': 'Bên mời thầu',
    'pakage.biddingType': 'Hình thức chọn nhà thầu',
    'pakage.contractType': 'Loại hợp đồng',
    'pakage.foundingSource': 'Nguồn vốn',
    'pakage.fromContractDate': 'T/gian HĐ bắt đầu',
    'pakage.toContractDate': 'T/gian HĐ kết thúc',
    'pakage.fromReceiveDate': 'T/gian nhận hồ sơ bắt đầu',
    'pakage.toReceiveDate': 'T/gian nhận hồ sơ kết thúc',
    'pakage.insuranceFee': 'Phí phát hành hồ sơ mời thầu',
    'pakage.receiveBidLocation': 'Địa điểm nhận hồ sơ dự thầu',
    'pakage.workeplace': 'Địa điểm thực hiện gói thầu',
    'pakage.openLocation': 'Địa điểm mở thầu', 
    'pakage.estimate': 'Dự toán gói thầu',
    'pakage.existed': 'Gói thầu đã tồn tại',
    'pakage.notfound': 'Không tìm thấy thông tin gói thầu',
    'pakage.biddingType.not.include': 'Gói thầu đã tồn tại',
    'pakage.notiType.invalid': 'Hình thức thông báo không đúng',
    'pakage.status.invalid': 'Trạng thái gói thầu không đúng',
    'bidding.cost': 'Giá đấu thầu',
    'bidding.entity': 'Nhóm đấu thầu',
    'bidding.startDate': 'Ngày bắt dầu',
    'bidding.endDate': 'Ngày kết thúc',
    'bidding.attackFiles': 'File đính kèm',
    'bidding.notfound': 'Không tìm thấy thông tin dự thầu',
    'bidding.existed': 'Đơn vị này đã tham dự đấu thầu',
  }
}
